apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-hulprfvm-gitops
  description: This is GitOps manifest for go-hulprfvm   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=go-hulprfvm
    backstage.io/kubernetes-id: go-hulprfvm 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: go-hulprfvm
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-hulprfvm
